In [24]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical 
import numpy as np 
import pandas as pd

from sklearn.preprocessing import minmax_scale 
from sklearn.model_selection import train_test_split

from keras.models import Sequential 
from keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import Adam
import itertools

In [25]:
file_directory='../Preprocess/data_after/'
#opposite과 my_team에 대한 변수를 두어 그 값이 1이면 내 팀, 0이면 다른 팀 인 방식으로 구현
#테스트 데이터는 match.csv의 result attribute를 사용
#train_data에 사용되는 데이터는 player1.csv의 선수의 티어 값을 이용


In [26]:
#match.csv 파일을 읽어서 팀의 승패 결과를 test 데이터로 활용
data=pd.read_csv("{0}match2.csv".format(file_directory))


data= data.loc[:,['gameid','side','result','dragons','barons','towers']]


#0는 레드
#1은 블루
cond1 = data['side']==0
cond2 = data['side']==1


X_test_blue = data[cond1]
X_test_red = data[cond2]




X_train = data[['dragons','barons','towers']]
#X_train_blue = data[['dragons','barons','towers']]
#X_train_red = data[['dragons','barons','towers']]
y_train = data['result']


print(X_train)
print(y_train)


X_train = X_train.to_numpy()
y_train = y_train.to_numpy()

x_train, x_test, y_train, y_test = train_test_split(X_train, y_train, random_state=66, test_size=0.2)



print(x_train.shape)
print(x_test.shape)
#print(X_test_blue)
#print(X_test_red)

#X_test_blue = X_test_blue.to_numpy()
#X_test_red = X_test_red.to_numpy()
#match.csv 파일에서 승패 결과 데이터인 result를 추출해내는 과정
#매치 데이터는 각 팀당 하나씩만 해서 표본 데이터를 가져온다.
'''for i in range(len(team)):
    for idx in X_test.index:
        if team[i]==X_test.loc[idx,'team']:
            y_test[i] = X_test.loc[idx,'result']
            break
            
#원핫 인코딩 적용
#y_test = to_categorical(y_test)

y_test = y_test.reshape(-1,1)'''


      dragons  barons  towers
0         0.0     1.0    10.0
1         0.0     0.0     4.0
2         0.0     1.0    10.0
3         0.0     0.0     2.0
4         0.0     0.0     1.0
...       ...     ...     ...
5277      1.0     1.0     4.0
5278      0.0     0.0     0.0
5279      4.0     1.0    10.0
5280      3.0     1.0     8.0
5281      0.0     0.0     2.0

[5282 rows x 3 columns]
0       1
1       0
2       1
3       0
4       0
       ..
5277    0
5278    0
5279    1
5280    1
5281    0
Name: result, Length: 5282, dtype: int64
(4225, 3)
(1057, 3)


"for i in range(len(team)):\n    for idx in X_test.index:\n        if team[i]==X_test.loc[idx,'team']:\n            y_test[i] = X_test.loc[idx,'result']\n            break\n            \n#원핫 인코딩 적용\n#y_test = to_categorical(y_test)\n\ny_test = y_test.reshape(-1,1)"

In [27]:
num_of_test_samples = x_test.shape[0] 
num_of_train_samples = x_train.shape[0]
print(num_of_test_samples)


#y_test 값은 one-hot encoding을 적용하였음


1057


In [28]:
y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
y_test = np.asarray(y_test).astype('float32').reshape((-1,1))

In [29]:
model = Sequential()

In [30]:
#input layer
model.add(Dense(32, input_shape = (num_of_train_samples,3), kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3)) 
for i in range(20):
    model.add(Dense(16, kernel_initializer='glorot_uniform', activation='relu'))
    model.add(Dropout(0.3))

In [31]:
print(X_train)
print(y_train)

[[ 0.  1. 10.]
 [ 0.  0.  4.]
 [ 0.  1. 10.]
 ...
 [ 4.  1. 10.]
 [ 3.  1.  8.]
 [ 0.  0.  2.]]
[[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [32]:
#마지막 hidden layer에 softmax activation function을 적용
model.add(Dense(1, activation='sigmoid'))#soft_max 

model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [34]:
training_epochs = 30 
batch_size = 100 
model.fit(x_train, y_train, epochs=training_epochs, batch_size=batch_size,validation_split=0.33)


Epoch 1/30
29/29 [==============================] - 0s 9ms/step - loss: 0.6778 - accuracy: 0.6148 - val_loss: 0.6865 - val_accuracy: 0.4946
Epoch 2/30
29/29 [==============================] - 0s 3ms/step - loss: 0.6532 - accuracy: 0.6922 - val_loss: 0.6747 - val_accuracy: 0.4946
Epoch 3/30
29/29 [==============================] - 0s 3ms/step - loss: 0.6180 - accuracy: 0.7216 - val_loss: 0.6754 - val_accuracy: 0.4946
Epoch 4/30
29/29 [==============================] - 0s 3ms/step - loss: 0.5901 - accuracy: 0.7530 - val_loss: 0.5767 - val_accuracy: 0.9262
Epoch 5/30
29/29 [==============================] - 0s 3ms/step - loss: 0.5610 - accuracy: 0.7820 - val_loss: 0.6686 - val_accuracy: 0.4946
Epoch 6/30
29/29 [==============================] - 0s 3ms/step - loss: 0.5694 - accuracy: 0.7806 - val_loss: 0.6084 - val_accuracy: 0.5935
Epoch 7/30
29/29 [==============================] - 0s 3ms/step - loss: 0.5276 - accuracy: 0.7961 - val_loss: 0.6178 - val_accuracy: 0.5484
Epoch 8/30
29/29 [==

In [36]:
evaluation = model.evaluate(x_test, y_test, batch_size=20) 
print('Accuracy: ' + str(evaluation[1]))


53/53 [==============================] - 0s 500us/step - loss: 0.4064 - accuracy: 0.8893
Accuracy: 0.8893093466758728
