In [6]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical 
import numpy as np 
import pandas as pd

from sklearn.preprocessing import minmax_scale 

from keras.models import Sequential 
from keras.layers import Dense, Dropout, Activation 
from tensorflow.keras.optimizers import Adam


In [21]:
file_directory='../Preprocess/data_after/'


(X_train, y_train), (X_test, y_test) = mnist.load_data() 
print(X_test)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [20]:
data=pd.read_csv("{0}match.csv".format(file_directory))
data = data.to_numpy()
X_train
print(data.shape)
X_train = data[:,7:12]
X_train

(26410, 12)


array([['Top', 'Daki', 'NiJun o-mFuro', 'Rumble', 1],
       ['Jungle', 'Wetch', 'NiJun o-mFuro', 'Jarvan IV', 1],
       ['Middle', 'Gguung', 'NiJun o-mFuro', 'Zed', 1],
       ...,
       ['Middle', 'FETI', 'Luuv SINDBAX', 'Lucian', 0],
       ['ADC', 'Pronci', 'Luuv SINDBAX', 'Samira', 0],
       ['Support', 'Iffurt', 'Luuv SINDBAX', 'Nautilus', 0]], dtype=object)

In [17]:
num_of_train_samples = X_train.shape[0] 
width = X_train.shape[1]    


(60000, 28, 28)


In [9]:
num_of_test_samples = X_test.shape[0]  
X_test = X_test.reshape(num_of_test_samples, width * height)

X_train = X_train.astype(np.float64) 
X_test = X_test.astype(np.float64) 

In [10]:
X_train = minmax_scale(X_train, feature_range=(0, 1), axis=0) 
X_test = minmax_scale(X_test, feature_range=(0, 1), axis=0) 
y_train = to_categorical(y_train) 
y_test = to_categorical(y_test)


In [11]:
model = Sequential()

In [13]:
#input layer
model.add(Dense(256, input_dim=width * height, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3)) 

In [14]:
#hidden layer 1
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))

In [15]:
#hidden layer 2
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))



In [16]:
#hidden layer 3
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))


In [17]:
number_of_class = 10 
model.add(Dense(number_of_class, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
training_epochs = 15 
batch_size = 100 
model.fit(X_train, y_train, epochs=training_epochs, batch_size=batch_size)


Epoch 1/15
600/600 [==============================] - 2s 3ms/step - loss: 0.3924 - accuracy: 0.8773
Epoch 2/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1747 - accuracy: 0.9494
Epoch 3/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1352 - accuracy: 0.9612
Epoch 4/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1153 - accuracy: 0.9671
Epoch 5/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1014 - accuracy: 0.9701
Epoch 6/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0911 - accuracy: 0.9735
Epoch 7/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0855 - accuracy: 0.9750
Epoch 8/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0785 - accuracy: 0.9772
Epoch 9/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0708 - accuracy: 0.9787
Epoch 10/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0673 - accuracy: 0.9801

In [20]:
evaluation = model.evaluate(X_test, y_test, batch_size=batch_size) 
print('Accuracy: ' + str(evaluation[1]))


100/100 [==============================] - 0s 950us/step - loss: 0.0749 - accuracy: 0.9809
Accuracy: 0.98089998960495
