In [42]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical 
import numpy as np 
import pandas as pd

from sklearn.preprocessing import minmax_scale 

from keras.models import Sequential 
from keras.layers import Dense, Dropout, Activation 
from tensorflow.keras.optimizers import Adam


In [58]:
file_directory='../Preprocess/data_after/'
#opposite과 my_team에 대한 변수를 두어 그 값이 1이면 내 팀, 0이면 다른 팀 인 방식으로 구현
#테스트 데이터는 match.csv의 result attribute를 사용
#train_data에 사용되는 데이터는 player1.csv의 선수의 티어 값을 이용
(X_train, y_train), (X_test, y_test) = mnist.load_data() 


print(X_train.shape)
print(y_train.shape)

print(X_train)
print(y_train)

print(X_test)
print(X_test.shape)
print(y_test)
print(y_test.shape)

(60000, 28, 28)
(60000,)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0 4 ... 5 6 8]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 

In [62]:

#player1.csv의 파일을 읽어서 각 팀별 플레이어 티어 평균값을 추출
data=pd.read_csv("{0}player1.csv".format(file_directory))
tier = data.loc[:,['Team','Tier']]
team = data.loc[:,'Team'].sort_index(axis=1)drop_duplicates()
AvgTier = tier.groupby('Team').mean()
X_train = AvgTier.to_numpy()
print(X_train)



0           Semsang Gelexy
2                 CJ Intas
3            SK Tilicum T1
5       Oncridobli Morecli
6      Jon Eor Griin Wongs
7            NeJon i-mFori
8               RUX Togirs
9               KT Rulstir
55             SBINA Kurie
64          Ribils Enerchy
131         Lungzha Gemong
133        Kungduu Munstir
134                i-mFori
140         Efriice Friics
206                    MBP
211               ISC Ivir
276            bbq Ulovirs
330          Ivir8 Wonnirs
393       Kongzuni DregunX
394            KSV iSpurts
461                Groffon
462                  Gin.G
468    Henwhe Lofi Ispurts
542           Loov SENDBUX
550                DWG KOE
690                    DRK
691      SiulHeiUni Pronci
693                     T2
774          Tiem Dynemocs
835      Nungshom RidFurci
837           Fridot BROUN
Name: Team, dtype: object
                         Tier
Team                         
CJ Intas             2.571429
DRK                  1.882353
DWG KOE          

In [53]:
#match.csv 파일을 읽어서 팀의 승패 결과를 test 데이터로 활용
data=pd.read_csv("{0}match.csv".format(file_directory))
X_test = data.loc[:,['side','team','result']]
X_test = X_test.to_numpy()
print(X_test.shape)

(26410, 3)


In [31]:
print(X_test.shape)

(26410,)


In [40]:
num_of_train_samples = X_train.shape[0] 
width = X_train.shape[1]    


In [42]:
num_of_test_samples = X_test.shape[0] 
print(num_of_test_samples)

906


In [11]:
model = Sequential()

In [13]:
#input layer
model.add(Dense(256, input_dim=width, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3)) 

In [14]:
#hidden layer 1
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))

In [15]:
#hidden layer 2
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))



In [16]:
#hidden layer 3
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))


In [17]:
number_of_class = 10 
model.add(Dense(number_of_class, activation='relu'))#soft_max 

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [19]:
training_epochs = 15 
batch_size = 100 
model.fit(X_train, y_train, epochs=training_epochs, batch_size=batch_size)


Epoch 1/15
600/600 [==============================] - 2s 3ms/step - loss: 0.3924 - accuracy: 0.8773
Epoch 2/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1747 - accuracy: 0.9494
Epoch 3/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1352 - accuracy: 0.9612
Epoch 4/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1153 - accuracy: 0.9671
Epoch 5/15
600/600 [==============================] - 2s 3ms/step - loss: 0.1014 - accuracy: 0.9701
Epoch 6/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0911 - accuracy: 0.9735
Epoch 7/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0855 - accuracy: 0.9750
Epoch 8/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0785 - accuracy: 0.9772
Epoch 9/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0708 - accuracy: 0.9787
Epoch 10/15
600/600 [==============================] - 2s 3ms/step - loss: 0.0673 - accuracy: 0.9801

In [20]:
evaluation = model.evaluate(X_test, y_test, batch_size=batch_size) 
print('Accuracy: ' + str(evaluation[1]))


100/100 [==============================] - 0s 950us/step - loss: 0.0749 - accuracy: 0.9809
Accuracy: 0.98089998960495
