In [131]:
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical 
import numpy as np 
import pandas as pd

from sklearn.preprocessing import minmax_scale 

from keras.models import Sequential 
from keras.layers import Dense, Dropout, Activation 
from tensorflow.keras.optimizers import Adam
import itertools

In [132]:
file_directory='../Preprocess/data_after/'
#opposite과 my_team에 대한 변수를 두어 그 값이 1이면 내 팀, 0이면 다른 팀 인 방식으로 구현
#테스트 데이터는 match.csv의 result attribute를 사용
#train_data에 사용되는 데이터는 player1.csv의 선수의 티어 값을 이용
(X_train, y_train), (X_test, y_test) = mnist.load_data() 


print(X_train.shape)
print(y_train.shape)

print(X_train)
print(y_train)

print(X_test)
print(X_test.shape)
print(y_test)
print(y_test.shape)

(60000, 28, 28)
(60000,)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0 4 ... 5 6 8]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 

In [157]:

#player1.csv의 파일을 읽어서 각 팀별 플레이어 티어 평균값을 추출
data=pd.read_csv("{0}player1.csv".format(file_directory))
tier = data.loc[:,['Team','Tier']]

team = data.sort_values('Team' ,ascending=True)
team = team.loc[:,'Team'].drop_duplicates()
team = team.to_list()
print(team)
AvgTier = tier.groupby('Team').mean()
AvgTier2 = np.random.rand(AvgTier.shape[0])
AvgTier2 = AvgTier2.reshape((31,1))*5
print(AvgTier2)


AvgTier = AvgTier.to_numpy()

Avg = np.zeros((31,2))

AvgTier = AvgTier.reshape(31)
AvgTier2 = AvgTier2.reshape(31)

Avg[:,0] = AvgTier
Avg[:,1] = AvgTier2


Answer = np.zeros(31)


for i in range(AvgTier.shape[0]):
    if AvgTier[i]<AvgTier2[i]:
        Answer[i] = 1
    else:
        Answer[i] = 0

print(Avg)
Answer = Answer.reshape((31,1))
print(Answer)

['CJ Intas', 'DRK', 'DWG KOE', 'Efriice Friics', 'Fridot BROUN', 'Gin.G', 'Groffon', 'Henwhe Lofi Ispurts', 'ISC Ivir', 'Ivir8 Wonnirs', 'Jon Eor Griin Wongs', 'KSV iSpurts', 'KT Rulstir', 'Kongzuni DregunX', 'Kungduu Munstir', 'Loov SENDBUX', 'Lungzha Gemong', 'MBP', 'NeJon i-mFori', 'Nungshom RidFurci', 'Oncridobli Morecli', 'RUX Togirs', 'Ribils Enerchy', 'SBINA Kurie', 'SK Tilicum T1', 'Semsang Gelexy', 'SiulHeiUni Pronci', 'T2', 'Tiem Dynemocs', 'bbq Ulovirs', 'i-mFori']
[[1.78883134]
 [4.60952047]
 [2.2977072 ]
 [1.17830484]
 [1.77295721]
 [1.64449551]
 [4.62373209]
 [1.51260863]
 [2.14557571]
 [0.38450405]
 [3.34106165]
 [1.6589373 ]
 [3.2411491 ]
 [3.94795031]
 [3.93775704]
 [3.50304002]
 [4.92025396]
 [0.11374055]
 [1.09701196]
 [2.08894976]
 [1.15857176]
 [1.73497676]
 [4.61568436]
 [3.93105205]
 [2.93329524]
 [4.50163785]
 [2.04833752]
 [4.41792697]
 [2.63842029]
 [2.14418288]
 [4.06636711]]
[[2.57142857 1.78883134]
 [1.88235294 4.60952047]
 [1.94117647 2.2977072 ]
 [2.51282

In [101]:
#match.csv 파일을 읽어서 팀의 승패 결과를 test 데이터로 활용
data=pd.read_csv("{0}match.csv".format(file_directory))
X_test = data.loc[:,['side','team','result']]
X_test = X_test.to_numpy()
print(X_test.shape)

(26410, 3)


In [102]:
print(X_test.shape)

(26410, 3)


In [103]:
num_of_train_samples = X_train.shape[0] 
width = X_train.shape[1]    


In [104]:
num_of_test_samples = X_test.shape[0] 
print(num_of_test_samples)

26410


In [105]:
model = Sequential()

In [106]:
#input layer
model.add(Dense(256, input_dim=width, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3)) 

In [107]:
#hidden layer 1
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu'))
model.add(Dropout(0.3))

In [108]:
#hidden layer 2
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))



In [109]:
#hidden layer 3
model.add(Dense(256, kernel_initializer='glorot_uniform', activation='relu')) 
model.add(Dropout(0.3))


In [110]:
number_of_class = 10 
model.add(Dense(number_of_class, activation='relu'))#soft_max 

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [111]:
training_epochs = 15 
batch_size = 100 
model.fit(X_train, y_train, epochs=training_epochs, batch_size=batch_size)


ValueError: Data cardinality is ambiguous:
  x sizes: 31
  y sizes: 60000
Make sure all arrays contain the same number of samples.

In [20]:
evaluation = model.evaluate(X_test, y_test, batch_size=batch_size) 
print('Accuracy: ' + str(evaluation[1]))


100/100 [==============================] - 0s 950us/step - loss: 0.0749 - accuracy: 0.9809
Accuracy: 0.98089998960495
